name: ayurcareprod
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  botion_flutter_plugin: ^0.0.2
  calendar_date_picker2: ^0.5.3
  cupertino_icons: ^1.0.2
  cupertino_stepper: ^0.2.1
  dark_light_button: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_analog_clock: ^1.0.3
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  formz: ^0.4.0
  get_it: ^7.6.7
  http: ^1.1.0
  intl: ^0.19.0
  primer_progress_bar: ^0.3.0
  responsive_builder: ^0.7.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  fonts:
    - family: GoogleFont
      fonts:
        - asset: fonts/Silkscreen/Silkscreen-Regular.ttf
        - asset: fonts/Silkscreen/Silkscreen-Bold.ttf
